### ISSUE TITLE
not able to create secret text type credentials

### ISSUE THREAD

**Issue by venky2k57** [samrocketman/jenkins-bootstrap-shared#13]
Hi,

Can you please let me know the exact snippet to add secret text type of credentials?

**Comment by sgleske-ias** [comment]
https://github.com/samrocketman/jenkins-bootstrap-jervis/blob/master/settings.groovy.EXAMPLE#L23-L43 contains an example.

See also:

* https://github.com/samrocketman/jenkins-bootstrap-jervis/blob/master/jervis_bootstrap.sh#L40
* https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/scripts/credentials-multitype.groovy

**Comment by samrocketman** [comment]
https://github.com/samrocketman/jenkins-bootstrap-jervis/blob/master/settings.groovy.EXAMPLE#L23-L43 contains an example.

See also:

* https://github.com/samrocketman/jenkins-bootstrap-jervis/blob/master/jervis_bootstrap.sh#L40
* https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/scripts/credentials-multitype.groovy
