### ISSUE TITLE
multi cloud provider Deployment 

### ISSUE THREAD

**Issue by Palme240** [samrocketman/jenkins-bootstrap-shared#15]
I'm new to the cloud. This is my internship subject. In my GitHub repository, i have two python lambda function, buildspec for CodePipeline(CodeBuild), template for CloudFormation. it works it deploys functions and an API on aws (creating and configure lambda functions trigger to API gateway with methods). it's serverless framework but now, I would like to no longer be dependent on AWS services.

I would like to deploy the same on other cloud provider.

what is the best CI / CD pipeline tools?

The serverless framework is still usable?

I would like to deploy to aws, Microsoft azure and google cloud

**Comment by samrocketman** [comment]
This is more of an issue tracker for bootstrapping Jenkins.  I recommend reaching asking these kinds of questions in r/devops or r/jenkinsci on reddit.
