### ISSUE TITLE
build folder are not there 

### ISSUE THREAD

**Issue by mohamedamraurea** [samrocketman/jenkins-bootstrap-shared#6]
Hi Sam, 

yesterday I've cloned the code today and built the image successfully .. but today there is an issue 

docker file has this line 

ADD build/distributions/*.tar /usr/

but build folder is not there

**Comment by samrocketman** [comment]
Hi, per the instructions in the README, you need to create the tar.

    ./gradlew buildTar

The following also works to generate all packaging formats.

    ./gradlew packages

**Comment by samrocketman** [comment]
See https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/README.md#build-a-docker-image

**Comment by mohamedamraurea** [comment]
Thanks Sam for your support 

do you have  sessions or webinars we can view to implement Jervis in our side 

Really it will really help. A video/Webinar session will be great 

Br,
Mohamed Amr

**Comment by samrocketman** [comment]
Currently, there are no plans for webinars or video tutorials.  At the moment, when I have spare time I develop Jervis to make it better.

This development includes:

* documentation
* examples
* code

Which keeps Jervis relevant in a rigorous workplace.  In the future, I may provide consulting on Jervis but I don't currently have any plans to do that either.  Should that be of interest to you, then feel free to contact me.
